version: '3.2'
services:

  postgres:
    image: postgres:9.2 
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - $PWD/sql_scripts/init_with_copy.sql:/docker-entrypoint-initdb.d/init_with_copy.sql

  configserver:
    image: dr.s.nuecho.com/configserver:d6f87b568191880e9970e67db382db12b1399878
    restart: on-failure
    environment:
      - PGPASSWORD=mysecretpassword
    depends_on:
      - postgres
    links:
      - postgres

  test:
    image: dr.s.nuecho.com/mutagen-integration-tests:latest
    depends_on:
      - configserver
    links:
      - configserver
    volumes:
      - $PWD/../build/mutagen:/usr/local/bin/mutagen
      - $PWD/environments.yml:/root/.mutagen/environments.yml:ro
      - $PWD/../tests:/usr/src/app/tests
