version: '3.2'
services:
  postgres_configserver:
    image: dr.s.nuecho.com/mutagen-postgres-configserver:9a5abebb3683b13dd6a1b1bc2f7df7bad8bbe81c

  configserver:
    image: dr.s.nuecho.com/genesys/config-server:8.5.1
    restart: on-failure
    environment:
      - PGPASSWORD=mysecretpassword
    depends_on:
      - postgres_configserver
    links:
      - postgres_configserver:postgres

  postgres_gax:
    image: dr.s.nuecho.com/mutagen-postgres-gax:f61ee9dc53178b9463e2b5dccbebe72640e83609

  gax:
    image: dr.s.nuecho.com/genesys/gax:8.5.2
    hostname: gax # Gax installer will automatically creates cfgHost object with that name
    depends_on:
      - postgres_gax
      - configserver
    links:
      - postgres_gax:postgres
      - configserver

  test:
    build:
      context: ./integration-tests
    environment:
      - CONFIG_SERVER_HOST=gax  # The container will wait for gax to be ready before running tests
      - CONFIG_SERVER_PORT=8080
    depends_on:
      - configserver
      - gax
    links:
      - configserver
      - gax
    volumes:
      - $PWD/../build/mutagen:/usr/local/bin/mutagen
      - $PWD/environments.yml:/root/.mutagen/environments.yml:ro
      - $PWD/gax_password:/tmp/gax_password:ro
      - $PWD/../tests:/usr/src/app/tests
