version: '3.2'
services:

  test:
    build: 
      context: ../
      dockerfile: ./docker/test/Dockerfile
    depends_on:
      - configserver
    links:
      - configserver
    environment:
      - MUTAGEN_PATH=mutagen
    volumes: 
      - ../package.json:/usr/src/app/package.json:ro
      - ../package-lock.json:/usr/src/app/package-lock.json:ro
      - ../tests:/usr/src/app/tests:ro
      - ../build/mutagen:/usr/bin/mutagen
      - ./environments.yml:/root/.mutagen/environments.yml:ro
