version: '3.2'
services:

  postgres:
    image: postgres:9.2 
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d

  configserver:
    image: dr.s.nuecho.com/configserver:d6f87b568191880e9970e67db382db12b1399878
    restart: on-failure
    environment:
      - PGPASSWORD=mysecretpassword
    depends_on:
      - postgres
    links:
      - postgres
