version: '3.2'
services:

  postgres_configserver:
    image: postgres:9.2 
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - $PWD/sql_scripts/configserver/:/docker-entrypoint-initdb.d/

  configserver:
    image: dr.s.nuecho.com/configserver:0.2.0
    restart: on-failure
    environment:
      - PGPASSWORD=mysecretpassword
    depends_on:
      - postgres_configserver
    links:
      - postgres_configserver:postgres

  postgres_gax:
    image: postgres:9.2
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - $PWD/sql_scripts/gax/:/docker-entrypoint-initdb.d/

  gax:
    image: dr.s.nuecho.com/gax:0.2.0
    hostname: gax # Gax installer will automatically creates cfgHost object with that name
    depends_on:
      - postgres_gax
      - configserver
    links:
      - postgres_gax:postgres
      - configserver

  test:
    image: dr.s.nuecho.com/mutagen-integration-tests:07ca1f476a193cfe0d8a77e292d99bedbf05f983
    depends_on:
      - configserver
    links:
      - configserver
    volumes:
      - $PWD/../build/mutagen:/usr/local/bin/mutagen
      - $PWD/environments.yml:/root/.mutagen/environments.yml:ro
      - $PWD/../tests:/usr/src/app/tests
