default:
  host: configserver
  user: default
  password: password

gax:
  host: gax
  port: 8080
  user: default
  password: password

invalidEncoding:
  host: configserver
  user: default
  password: password
  encoding: test
