package com.nuecho.genesys.cli.models.configuration

const val ALIAS = "alias"
const val AUTO_RESTART = "autoRestart"
const val ALARM_DETECT_EVENT = "alarmDetectEvent"
const val ALARM_DETECT_EVENT_LOG_EVENT_ID = "alarmDetectEvent.logEventID"
const val CATEGORY = "category"
const val CHANNEL = "channel"
const val CODE = "code"
const val DISPLAY_NAME = "displayName"
const val FIELD_TYPE = "fieldType"
const val GROUP = "group"
const val IS_PARENT_NSP = "isParentNSP"
const val PHYSICAL_SWITCH = "physicalSwitch"
const val REDUNDANCY_TYPE = "redundancyType"
const val RESELLER = "reseller"
const val ROUTE_TYPE = "routeType"
const val SOLUTION_TYPE = "solutionType"
const val TENANT = "tenant"
const val TYPE = "type"
const val USER_NAME = "userName"
const val VERSION = "version"
